#!/usr/bin/env ruby
require 'optparse'
require 'sms_backup_renderer'

optparse = OptionParser.new do |opts|
  opts.banner = 'Usage: sms_backup_renderer INPUT_FILE OUTPUT_DIR [options]'

  opts.on('--version', "Print program version and exit") do
    puts "sms_backup_renderer #{SmsBackupRenderer::VERSION}"
    exit 0
  end
end

optparse.parse!
if ARGV.length != 2
  puts optparse
  exit -1
end

input_file_path = ARGV.shift
output_dir_path = ARGV.shift

SmsBackupRenderer.generate_html_from_archive(input_file_path, output_dir_path)
